text_settings = {
    "system.Please_send_data_using_post_method": "Please send data using post method.",
    "system.page_not_found": "Page not found",
    "system.otp_sms": "Use this code for Khel11 verification ",
    "user.userid_required":"user id is required",
    "post.added": "Post is successfully added",
    "user.phone_already_exists":"phone number already exists",
    "system.unauthorized":"Unauthorized",
    "user.postId_required": "Post id is required",
    "user.avatarId_required": "Avatar id is required",
    "user.otp_required":"please enter otp",
    "post.edited": "Post edited",
    "user.verifyOtpType_required":"verifyOtpType required",
    "avtars.no_record_exists":"Record not Found",
    "post.post_is_not_exists": "Post is not exists.",
    "user.isMark_required": "is mark reuqired",
    "user.page_required":" Page is required",
    "user.verify_otp":"verify otp",
    "user.otp_not_found":"otp not found",
    "user.otp_not_valid":"otp is invalid",
    "user.otp_verified":"otp is verified",
    "user.login_succeeded":"login succeeded",
    "user.otp_expired":"otp expired",
    "user.otp_already_verified":"otp has been already verified",
    "user.not_found":"user not found",
    "user.resend_otp":"resend otp",
    "user.phone_required":"Phone number is required",
    "user.not_registered":"user is not registered",
    "post.bookmark_status_updated": "Bookmark status updated",
    "post.post_deleted": "Post deleted successfully",
    "post.liked": "Post liked",
    "user.name_required":"Name is required",
    "user.blocked":"user blocked",
    "user.profile_updated":"profile is updated",
    "user.providerKey_required":"provider key is required",
    "user.providerType_required":"providerType is required",
    "user.add_phone":"add phone",
    "post.unliked": "Post unliked",
    "Invalid File Format":"Invalid File Format",
    "comment.added": "Comment is successfully added",
    "user.contestId_required": "Contest id is required",
    "comment.not_exists":"Does Not Exist",
    "comment.edited": "Comment edited",
    "comment.comment_is_not_exists": "Comment is not exists.",
    "comment.comment_deleted": "Record Updated successfully",
    "contest.submitted": "You have succesfully participated in contest. Admin will contact you if you will be the winner.",

    "poll.id_required":"Poll id is required",
    "comment.liked": "Comment liked",
    "comment.unliked": "Comment unliked",
    "reply.added": "Reply added",
    "user.replyId_required": "Reply id required",
    "reply.reply_deleted": "Reply deleted",
    "reply.edited": "Reply edited successfully",
    "reply.liked": "Reply liked",
    "reply.unliked": "Reply unliked",
    "type_required": "Type is required",
    "user.record_does_not_exists": "Record does not exists",
    "user.categoryId_required": "Category id required",
    "reply.you_cant_reply_on_this_comment_because_this_comment_is_not_exists_now": "You can't reply on this comment because this comment is not exists now",
    "user.flag_required": "flag required",
    "reply.unliked_removed": "reply unlike removed",
    "reply.liked_removed": "reply like removed",
    "comment.unliked_removed": "comment unlike removed",
    "comment.liked_removed": "comment like removed",
    "post.unliked_removed": "post unlike removed",
    "post.liked_removed": "post like removed",
    "post.page_required": "Please enter valid page number",
    "post.show_recent_required": "Please pass valid boolean value",
    "user.isSearched_required": "isSearched required",
    "user.id_required": "Id is required",
    "deviceToken_required": "device token required",
    "isMute_required": "isMute is required",
    "app.appVersion_required": "App version required",
    "app.os_required": "OS required",
    "app.isUpdate_required": "IsUpdate required",
    "app.isForceUpdate_required": "IsForceUpdate required",
    "app.added": "Record added successful",
    "app.updated": "Record updated successful",
    "app.exists": "Record already exists",
    "app.exist.username": "username already exists",
    "app.exist.email": "email already exists",
    "app.exist.phone": "phone number already exists",
    "app.record_not_found": "Record not found",
    "system.something_went_wrong": "Something went wrong",
    "account.required": "Notification status required",
    "account.deviceId_required": "devicce id required",
    "common.status_updated": "Status updated",
    "common.matchId_req": "MatchId required",
    "common.live_stream_url_req": "Live stream URL required",
    "common.match_exists": "Match already exists",
    "common.added": "Record added",
    "common.match_format_req": "Match format required",
    "user.already_exists":"user already exist",
    "user.please_verify_otp":"Please verify OTP"
};
